name: image_editor
description: Edit your image data and output to file/memory on Android and iOS.
version: 1.6.0
repository: https://github.com/fluttercandies/flutter_image_editor

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  image_editor_platform_interface: ^1.1.0
  image_editor_common: ^1.2.0
  image_editor_ohos: ^0.0.9
  # image_editor_common:
  #   path: ../image_editor_common
  # image_editor_platform_interface:
  #   path: ../image_editor_platform_interface
  # image_editor_ohos:
  #   path: ../image_editor_ohos
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        default_package: image_editor_common
      ios:
        default_package: image_editor_common
      macos:
        default_package: image_editor_common
      ohos:
        default_package: image_editor_ohos
