name: image_editor_common
description: Edit your image data and output to file/memory on Android and iOS.
version: 1.2.0
repository: https://github.com/fluttercandies/flutter_image_editor

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  image_editor_platform_interface: ^1.1.0
  # image_editor_platform_interface: ^1.0.0
  # path: ../image_editor_platform_interface

dev_dependencies:
  flutter_lints: any

flutter:
  plugin:
    implements: image_editor
    platforms:
      android:
        package: com.fluttercandies.image_editor
        pluginClass: ImageEditorPlugin
        dartPluginClass: ImageEditorCommon
      ios:
        pluginClass: ImageEditorPlugin
        dartPluginClass: ImageEditorCommon
      macos:
        pluginClass: ImageEditorPlugin
        dartPluginClass: ImageEditorCommon
