# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
      - "*-v[0-9]+.[0-9]+.[0-9]+*" # tag pattern on pub.dev: 'v{{version}'

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: "Publish"
        run: python3 publish.py ${{ github.ref }}
