name: Runnable (stable)

on:
  pull_request:

jobs:
  analyze:
    name: Analyze code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Log Dart/Flutter versions
        run: |
          dart --version
          flutter --version
      - name: Run the runnable shell
        run: sh -e ./runnable.sh

  test_iOS:
    needs: analyze
    name: Test iOS build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: dart --version
      - run: flutter --version
      - run: cd image_editor; flutter pub get
      - run: cd image_editor/example; flutter build ios --no-codesign

  test_Android:
    needs: analyze
    name: Test Android build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: dart --version
      - run: flutter --version
      - run: cd image_editor; flutter pub get
      - run: cd image_editor/example; flutter build apk --debug

  test_macOS:
    needs: analyze
    name: Test macOS build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: dart --version
      - run: flutter --version
      - run: cd image_editor; flutter pub get
      - run: cd image_editor/example; flutter build macos --debug
